node {

  stage ('git checkout') {
        git branch: 'main', url: 'https://github.com/NKCloudDevOps/Terraform-main-veera.git'
  
  }

  stage ('tf init'){
        dir('day-2-basic_code'){
        sh 'terraform init'
 }
}

  stage ('tf plan') {
        dir('day-2-basic_code'){
        sh 'terraform plan'
  }
  }
  stage ('tf apply') {
        dir('day-2-basic_code'){
        sh 'terraform apply -auto-approve'
  }
  }

}
